---
layout: cv
title: Isaac Newtons's CV
---
# Isaac Newton
Physicist, Mathematician, Cambridge professor.

<div id="webaddress">
<a href="isaac@applesdofall.org">isaac@applesdofall.org</a>
| <a href="http://en.wikipedia.org/wiki/Isaac_Newton">My wikipedia page</a>
</div>


### Sariah Daly

__410.446.2849 • sariah.daly.vet@gmail.com • www.linkedin.com/Sariahdaly__

## Currently

I am pursuing a major in Pre-Vet and a certificate in Data Science full-time at Brigham Young University - Idaho. I actively get involved in and alternate between various campus organizations like Ballroom dance, Pre-Vet Society, and Peer Mentoring. Next semester I have been hired to tutor for CHEM 105.

## Education

`2021 - NOW`
__Brigham Young University - Idaho.__

- Bachelors of Animal Science: Pre-Vet
- Certificate in Data Science

`Fall 2024 - NOW`
__BYU-I Pre-Vet Society.__

- Secretary [Fall 2024]

`Fall 2023`
__Heber J. Grant Peer Mentor.__

`Spring 2023 - Spring 2024`
__Ballroom Dance Instructor.__

- Manager (Spring 2024)

## Work Experience

`May 2023 – August 2023`
__Church Camp Counselor__, Provo, UT
<br>*For The Strength of Youth Program – Brigham Young University*

- Taught material from the provided handbook with inspired changes from related sources
- Provided enriching activities and learning to youth to connect with their faith
- Communicated with Assistant Coordinators, Coordinators, and other leadership to ensure connection
- Exhibited positivity, patience, and flexibility in times of unpredictability and error
- Catered to youth's individual spiritual, physical, and emotional needs

`December 2022 – June 2023`
__Inventory Manager__, Rexburg, ID
<br>*Righteous Slice*

- Compiled Cost of Goods Sold, Sales, and Labor data into a Prime Cost report for owner
- Designed an Excel dashboard to visualize historical, present and future sales data
- Created a spreadsheet to track details about each item and ensure standardized training in the future
- Tracked inventory in the restaurant to determine what par levels of each item is needed for the week
- Communicated with supplier representative to lower prices by 10-20% on more than 20 items
- Submit orders to suppliers to achieve lowest price possible while maintaining quality

`May 2021 - August 2021`
__Executive Assistant__, Annapolis Junction, MD
<br>*TurboHaul*

- Assembled Excel sheets for inventory and led research on collections, earned $895 from selling items in a month
- Corresponded with President of the company and communicated with clients about accounts receivable, recovered over $5000 owed to the business
- Reconciled and applied payments, performed data entry, organized human resource files for 50+ employees 


<!-- ### Footer

Last updated: May 2013 -->